### ISSUE TITLE
Incorrect Name/Platform

### ISSUE THREAD

**Issue by Nielk1** [Nielk1/GameLaunchProxy#4]
We have an instance of an incorrectly named game coming through.  Waiting on user to enable logging and provide GameLaunchProxy.log, names_launchbox.json, and settings.json files.

If anyone else has such an issue, please enable logging, trigger the error, and then supply these files.

**Comment by cammelspit** [comment]
Here are the requested files for your enjoyment. :) I apparently already had logging enabled.

[Proxy log for incorrect platform label.zip](https://github.com/Nielk1/GameLaunchProxy/files/466190/Proxy.log.for.incorrect.platform.label.zip)

**Comment by Nielk1** [comment]
Corrected in 0.0.3.1 via having the LaunchBox Library scraper look inside zips.
